version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./src:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/usr/share/nginx/html